#El nombre con el punto se pone para que esté oculto para los usuarios
projects:
  app:
    schemaPath: src/schema.graphql
    extensions: 
      endpoints:
        default: http://localhost:4000
        #Esto me está dicniendo que voy a tener un schema.graphql corriendo en el puerto 4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: src/database/prisma.yml